export interface Env {
  DB: D1Database;
  CONTEXT_INDEX: VectorizeIndex;
  AI: Ai;

  SLACK_BOT_TOKEN: string;
  SLACK_SIGNING_SECRET: string;
  POSTHOG_API_KEY: string;
  POSTHOG_PROJECT_ID: string;
  POSTHOG_HOST?: string;

  /** Optional: if set, RAG answers are generated by the Anthropic API
   * instead of the free Workers AI model. See src/rag/generate.ts. */
  ANTHROPIC_API_KEY?: string;

  /** Optional: if set (and ANTHROPIC_API_KEY isn't), RAG answers are
   * generated via OpenRouter, which gives you a choice of cheap/free models
   * behind one API instead of committing to one provider. See
   * src/rag/generate.ts. */
  OPENROUTER_API_KEY?: string;
  OPENROUTER_MODEL?: string;

  /** Bearer token required on POST /ingest. Unset by default so a fresh
   * deploy doesn't accidentally accept writes from anyone who finds the
   * URL — set it with `wrangler secret put INGEST_API_KEY` before wiring
   * up a connector (Intercom, Zendesk, a call-notes export, ...). */
  INGEST_API_KEY?: string;

  /** Fireflies.ai meeting-transcript connector — see src/connectors/fireflies.ts.
   * Both unset by default (fail closed, like INGEST_API_KEY). */
  FIREFLIES_API_KEY?: string;
  FIREFLIES_WEBHOOK_SECRET?: string;

  /** Zoom cloud-recording transcript connector — see src/connectors/zoom.ts. */
  ZOOM_WEBHOOK_SECRET_TOKEN?: string;

  /** Google Meet transcript connector (Workspace domain-wide delegation
   * service account) — see src/connectors/google-meet.ts. */
  GOOGLE_SERVICE_ACCOUNT_EMAIL?: string;
  GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY?: string;
  GOOGLE_WORKSPACE_IMPERSONATE_EMAIL?: string;
}
