export interface Env {
  DB: D1Database;
  CONTEXT_INDEX: VectorizeIndex;
  AI: Ai;

  SLACK_BOT_TOKEN: string;
  SLACK_SIGNING_SECRET: string;
  POSTHOG_API_KEY: string;
  POSTHOG_PROJECT_ID: string;
  POSTHOG_HOST?: string;

  /** "posthog" (default) or "mixpanel" — see src/usage.ts. Only the
   * matching provider's vars below need to be set. */
  USAGE_PROVIDER?: string;
  MIXPANEL_PROJECT_ID?: string;
  MIXPANEL_SERVICE_ACCOUNT_USERNAME?: string;
  MIXPANEL_SERVICE_ACCOUNT_SECRET?: string;
  MIXPANEL_HOST?: string;
  MIXPANEL_ACTIVE_EVENT_NAME?: string;
  MIXPANEL_ACCOUNT_PROPERTY?: string;

  /** Optional: if set, RAG answers are generated by the Anthropic API
   * instead of the free Workers AI model. See src/rag/generate.ts. */
  ANTHROPIC_API_KEY?: string;

  /** Optional: if set (and ANTHROPIC_API_KEY isn't), RAG answers are
   * generated via OpenRouter, which gives you a choice of cheap/free models
   * behind one API instead of committing to one provider. See
   * src/rag/generate.ts. */
  OPENROUTER_API_KEY?: string;
  OPENROUTER_MODEL?: string;

  /** Bearer token required on POST /ingest. Unset by default so a fresh
   * deploy doesn't accidentally accept writes from anyone who finds the
   * URL — set it with `wrangler secret put INGEST_API_KEY` before wiring
   * up a connector (Intercom, Zendesk, a call-notes export, ...). */
  INGEST_API_KEY?: string;

  /** Fireflies.ai meeting-transcript connector — see src/connectors/fireflies.ts.
   * Both unset by default (fail closed, like INGEST_API_KEY). */
  FIREFLIES_API_KEY?: string;
  FIREFLIES_WEBHOOK_SECRET?: string;

  /** Zoom cloud-recording transcript connector — see src/connectors/zoom.ts. */
  ZOOM_WEBHOOK_SECRET_TOKEN?: string;

  /** Google Meet transcript connector (Workspace domain-wide delegation
   * service account) — see src/connectors/google-meet.ts. */
  GOOGLE_SERVICE_ACCOUNT_EMAIL?: string;
  GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY?: string;
  GOOGLE_WORKSPACE_IMPERSONATE_EMAIL?: string;

  /** Intercom support-conversation connector — see src/connectors/intercom.ts. */
  INTERCOM_ACCESS_TOKEN?: string;
  /** Not a credential — the workspace id in Intercom's own URLs. Set it and
   * every Intercom citation becomes a link to the conversation. */
  INTERCOM_APP_ID?: string;
  INTERCOM_CLIENT_SECRET?: string; // signs webhook deliveries

  /** Zendesk support-ticket connector — see src/connectors/zendesk.ts. */
  ZENDESK_SUBDOMAIN?: string; // "yourcompany" in yourcompany.zendesk.com — also what makes Zendesk citations linkable
  ZENDESK_EMAIL?: string; // agent/admin email the API token belongs to
  ZENDESK_API_TOKEN?: string;
  ZENDESK_WEBHOOK_SECRET?: string; // shared secret you choose, same pattern as Fireflies

  /** HubSpot CRM notes/engagements connector (nightly backfill, like
   * Google Meet — see src/connectors/hubspot.ts). */
  HUBSPOT_ACCESS_TOKEN?: string; // private app token
  /** Not a credential — the portal/hub id in every app.hubspot.com URL.
   * Set it and HubSpot citations link to the note. */
  HUBSPOT_PORTAL_ID?: string;

  /** Salesforce CRM connector — logged calls/emails/meetings (Task records)
   * against an Account. OAuth2 client-credentials, so all three are needed:
   * the org's instance URL plus an External Client App's key and secret.
   * See src/connectors/salesforce.ts. */
  SALESFORCE_INSTANCE_URL?: string; // e.g. https://acme.my.salesforce.com
  SALESFORCE_CLIENT_ID?: string;
  SALESFORCE_CLIENT_SECRET?: string;

  /** Attio CRM connector — notes written on company records. Nightly
   * backfill, see src/connectors/attio.ts. */
  ATTIO_API_KEY?: string;

  /** Issue tracker — where an approved ticket draft gets filed. Optional:
   * without one, drafts can still be written and reviewed, just not filed. */
  TRACKER_PROVIDER?: string; // "linear" | "jira"; inferred when only one is configured
  LINEAR_API_KEY?: string;
  LINEAR_TEAM_ID?: string;
  JIRA_SITE_URL?: string; // https://yourcompany.atlassian.net
  JIRA_EMAIL?: string;
  JIRA_API_TOKEN?: string;
  JIRA_PROJECT_KEY?: string;
  JIRA_ISSUE_TYPE?: string; // defaults to "Task"

  /** Gates the /setup wizard (src/setup/) — set this BEFORE your first
   * deploy. Anyone with this token can view and change every connector
   * credential through the UI, so treat it like an admin password. */
  SETUP_ADMIN_TOKEN?: string;

  /** Slack channel ID (not name) alerts get posted to when an account's
   * health tier changes — see src/alerts.ts. Settable via the setup UI or
   * as a Workers secret; unset = alerting is off. */
  SLACK_ALERTS_CHANNEL?: string;

  /** Microsoft Teams bot — see src/teams/. From your Azure Bot resource
   * (Bot Framework "App ID" / "App Password", a.k.a. the Azure AD app
   * registration's client ID/secret). Both required to run the Teams bot
   * at all: the ID to verify incoming tokens are addressed to you, the
   * password to get an outbound token to actually reply. */
  MICROSOFT_APP_ID?: string;
  MICROSOFT_APP_PASSWORD?: string;

  /** Bearer token required on POST /mcp — the same account-context tools
   * @Bell answers from in Slack/Teams, exposed over MCP for coding agents
   * (Claude Code, Cursor, Codex, OpenCode). Unset by default, same
   * fail-closed pattern as INGEST_API_KEY. See src/mcp/server.ts. */
  MCP_ACCESS_TOKEN?: string;
}
